#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := AWS_IoT_Kit-AmazonConnect_AgentStatus
PROJECT_VER := 1.2.1

include $(IDF_PATH)/make/project.mk

